<?php
/** @var Template $block */
/** @var Escaper $escaper */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Snowdog\Hyva\Checkout\TPay\ViewModel\TpayCards;

/** @var TpayCards $viewModel */
$viewModel = $block->getData('viewModel');
?>

<div x-data="snowdogHyvaCheckoutTPayComponentPaymentMethodTpayCardForm" data-hyvacsp1="<?= $viewModel->getPublicKey() ?>" data-hyvacsp2="<?= $escaper->escapeHtmlAttr(__('Sorry, your credit card type is currently not supported. Please try another payment method.')) ?>" data-hyvacsp3="<?= $escaper->escapeHtmlAttr(__('Your credit card number seems to be invalid.')) ?>" x-init="snowdogHyvaCheckoutTPayComponentPaymentMethodTpayCardFormInit4" id="card_payment_form" class="tpay-channel-form-wrapper tpay-content-wrapper-class">
    <div id="card_form" x-show="open" @tpay-card-new.window="snowdogHyvaCheckoutTPayComponentPaymentMethodTpayCardFormTpayCardNewWindow5">
        <div id="card_payment" class="tpay-input-wrapper">
            <div class="tpay-col">
                <div class="tpay-row">
                    <div class="tpay-input-wrapper">
                        <div class="tpay-input-credit-card-number">
                            <div class="tpay-input-label"><?= __('Card number') ?></div>
                            <input id="card_number"
                                   pattern="\d*"
                                   autocomplete="cc-number"
                                   @change="recalulate"
                                   @keyup="recalulate"
                                   :value="cc_number" @change="snowdogHyvaCheckoutTPayComponentPaymentMethodTpayCardFormChange6"
                                   size="30"
                                   type="tel"
                                   maxlength="23"
                                   placeholder="XXXX XXXX XXXX XXXX"
                                   tabindex="1"
                                   value=""
                                   class="tpay-input-value"
                                   :class="cc_number_valid"
                            />
                            <div class="tpay-card-icon " :class="cc_type"></div>
                        </div>
                    </div>
                </div>

            </div>
            <div class="tpay-col">
                <div class="tpay-row">
                    <div class="tpay-expiration-date-input tpay-input-wrapper">
                        <div class="tpay-input-label">
                            <?= __('Expiration date') ?>
                        </div>
                        <input id="expiry_date"
                               maxlength="9"
                               type="tel"
                               placeholder="01 / 2020"
                               @change="recalulate"
                               @keyup="recalulate"
                               :value="cc_exp" @change="snowdogHyvaCheckoutTPayComponentPaymentMethodTpayCardFormChange7"
                               autocomplete="cc-exp"
                               tabindex="2"
                               value=""
                               class="tpay-input-value"
                               :class="cc_exp_valid"
                        />
                    </div>
                    <div class="tpay-cvv-input tpay-input-wrapper">
                        <div class="tpay-input-label tpay-input-cvc"
                             title="<?= __(
                                 'For MasterCard, Visa or Discover, these are the last three digits placed next to the card user signature.'
                             ) ?>"
                        >
                            <?= __('CVC') ?>
                        </div>
                        <input id="cvc"
                               maxlength="3"
                               type="tel"
                               @change="recalulate"
                               @keyup="recalulate"
                               :value="cc_ccv" @change="snowdogHyvaCheckoutTPayComponentPaymentMethodTpayCardFormChange8"
                               autocomplete="cc-cvc"
                               placeholder="XXX"
                               tabindex="3"
                               value=""
                               class="tpay-input-value"
                               :class="cc_ccv_valid"
                        />
                    </div>
                </div>
            </div>
        </div>
        <p id="info_msg" x-text="message"></p>
        <?php if ($viewModel->canSaveCC()): ?>
            <div class="tpay-amPmCheckbox" id="tpay-card-save-checkbox">
                <input type="checkbox" id="card_save" name="card_save" :value="save" @change="snowdogHyvaCheckoutTPayComponentPaymentMethodTpayCardFormChange9" @change="recalulate"/>
                <label for="card_save" class="tpay-info-label" title="<?= __(
                    'Allow to pay faster for next orders. Card data will be stored on secure tpay.com server.'
                ) ?>">
                    <?= __('Save my card') ?>
                </label>
            </div>
        <?php endif ?>
    </div>
</div><script>
<?php /** Generated with hyva-csp-helper.php */ ?>
function snowdogHyvaCheckoutTPayComponentPaymentMethodTpayCardForm() {
    return Object.assign(
        {
open:false,
cc_number: '',
cc_number_valid: '',
cc_type: '',
cc_exp: '',
cc_exp_valid: '',
cc_ccv: '',
cc_ccv_valid: '',
message: '',
save: false,
rsa: `${this.$el.dataset.hyvacsp1}`,
recalulate() {
    var this.formated = replace(/\this.s/this.g, '');
    if (this.formated.length > 1 ) {
        this.formated = replace(/^([0-9]{0,4})([0-9]{0,4})([0-9]{0,4})([0-9]{0,4})(\this.d*)$/, '$1 $2 $3 $4 $5').trim();
        if (this.formated != this.cc_number) this.cc_number = this.formated;
        var this.type = getType();
        if (this.type == 'unknown') {
            this.message = `${this.$el.dataset.hyvacsp2}`;
            this.cc_number_valid = 'wrong';
            return;
        }
        if (!luhnCheck(replace(/\this.s/this.g, ''))) {
            this.message = `${this.$el.dataset.hyvacsp3}`;
            this.cc_number_valid = 'wrong';
            return;
        }
        this.cc_number_valid = 'valid';

    } this.else {
        this.cc_number_valid = '';
    }
    this.message = '';
    var this.formated = replace(/\this.s/this.g, '');
    if (this.formated.length > 1 ) {
        if (!match(/^[01]/)) this.formated = '0' + this.formated;
        this.formated = replace(/^([0-9]{0,2})([0-9]{0,4})$/, '$1 / $2');
        if (this.formated != this.cc_exp) this.cc_exp = this.formated;
        var this.data = split('/');
        if (this.data.length != 2) {
            this.cc_exp_valid = 'wrong';
            return;
        }
        var this.month = this.data[0].trim(), this.year = this.data[1].trim();
        if (!((1 <= this.month && this.month <= 12))) {
            this.cc_exp_valid = 'wrong';
            return;
        }
        if (this.year.length === 2) {
            if (this.year < 70) {
                this.year = '20' + this.year;
            } this.else {
                this.year = '19' + this.year;
            }
        }
        if (this.year.length !== 4) {
            this.cc_exp_valid = 'wrong';
            return;
        }
        this.expiry = new Date(this.year, this.month);
        this.currentTime = new Date;
        setMonth(getMonth() - 1);
        setMonth(getMonth() + 1, 1);
        if (this.expiry > this.currentTime) {
            this.cc_exp_valid = 'valid';
        } this.else {
            this.cc_exp_valid = 'wrong';
            return;
        }
    } this.else {
        this.cc_exp_valid = '';
    }

    this.formated = replace(/\this.s/this.g, '');
    if (this.formated.length > 1) {
        this.cc_ccv_valid = this.formated.length == 3 ? 'valid' : 'wrong';
    } this.else {
        this.cc_ccv_valid = '';
    }


     var this.encrypt = new JSEncrypt(),
        this.decoded = atob(this.rsa),
        this.cn = replace(/\this.s/this.g, ''),
        this.ed = replace(/\this.s/this.g, ''),
        this.cvc = replace(/\this.s/this.g, ''),
        this.cd = this.cn + '|' + this.ed + '|' + this.cvc + '|' + document.location.origin;
     if ( this.cn !== '' && this.ed !== '' && this.cvc != '') {
        setPublicKey(this.decoded);
        find('checkout.payment.method.Tpay_Magento2_Cards.Cards').preserveToken(encrypt(this.cd), this.cc_type, slice(-4), this.save)
    }
},
getType() {
    var this.number = replace(/\this.s/this.g, '');
    if (startsWith('4')) {
        this.cc_type = 'tpay-visa-icon';
        return 'visa';
    }
    for(this.prefix this.of ['51', '52', '53', '54', '55', '22', '23', '24', '25', '26', '27']) {
        if(startsWith(this.prefix)) {
            this.cc_type = 'tpay-mastercard-icon';
            return 'mastercard';
        }
    }
    for(this.prefix this.of ['50', '57', '56', '58', '6']) {
        if(startsWith(this.prefix)) {
            this.cc_type = 'tpay-maestro-icon';
            return 'maestro';
        }
    }
    this.cc_type = '';
    return 'unknown';
},
luhnCheck(num) {
    var this.digit, this.digits, this.odd, this.sum, _i, _len;
    this.odd = true;
    this.sum = 0;
    this.digits = (this.num + '').split('').reverse();
    this.for (_i = 0, _len = this.digits.length; _i < _len; _i++) {
        this.digit = this.digits[_i];
        this.digit = parseInt(this.digit, 10);
        if ((this.odd = !this.odd)) {
            this.digit *= 2;
        }
        if (this.digit > 9) {
            this.digit -= 9;
        }
        this.sum += this.digit;
    }
    return this.sum % 10 === 0;
}
}
        ,{
            ['snowdogHyvaCheckoutTPayComponentPaymentMethodTpayCardFormChange6'](event) {return this.cc_number = this.$el.value},
            ['snowdogHyvaCheckoutTPayComponentPaymentMethodTpayCardFormChange7'](event) {return this.cc_exp = this.$el.value},
            ['snowdogHyvaCheckoutTPayComponentPaymentMethodTpayCardFormChange8'](event) {return this.cc_ccv = this.$el.value},
            ['snowdogHyvaCheckoutTPayComponentPaymentMethodTpayCardFormChange9'](event) {return this.save = this.$el.value},
            ['snowdogHyvaCheckoutTPayComponentPaymentMethodTpayCardFormInit4']() {return this.open = document.getElementById('newCard').checked},
            ['snowdogHyvaCheckoutTPayComponentPaymentMethodTpayCardFormTpayCardNewWindow5'](event) {return this.open = document.getElementById('newCard').checked},
        }
    )
}
window.addEventListener('alpine:init', () => Alpine.data('snowdogHyvaCheckoutTPayComponentPaymentMethodTpayCardForm', snowdogHyvaCheckoutTPayComponentPaymentMethodTpayCardForm), {once: true});
</script>
<?php $hyvaCsp->registerInlineScript() ?>